version: "3"
services:
  mydockerapp:
    image: jesse111/compose-crud-spring-service:1.0
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - docker-mysql
    environment:
      - MYSQL_HOST=docker-mysql
  docker-mysql:
    image: mysql:oracle
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ~/apps/mysql:/var/lib/mysql